from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Table,
    TableStyle,
    Paragraph,
    Spacer
)
from datetime import datetime
from reportlab.platypus import Image
import os


def generate_pdf(voltage, current, frequency, temperature, fault, confidence, health):

    # -------------------------------
    # Create PDF File
    # -------------------------------
    filename = f"GridGuard_Report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"

    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    elements = []

    # -------------------------------
    # Report ID
    # -------------------------------
    report_id = "GG-" + datetime.now().strftime("%Y%m%d-%H%M%S")

    # -------------------------------
    # Header
    # -------------------------------
    title = Paragraph(
        "<font color='darkblue'><b><font size=22>⚡ GRIDGUARD AI</font></b></font>",
        styles["Title"]
    )

    subtitle = Paragraph(
        "<b>Smart Grid Fault Detection Report</b>",
        styles["Heading2"]
    )

    info = Paragraph(
        f"""
        <b>Report ID:</b> {report_id}<br/>
        <b>Generated:</b> {datetime.now().strftime('%d-%m-%Y %H:%M:%S')}
        """,
        styles["Normal"]
    )

    # -------------------------------
# GridGuard AI Logo
# -------------------------------

    if os.path.exists("assets/logo.png"):

        logo = Image(
            "assets/logo.png",
            width=80,
            height=80
        )

        elements.append(logo)

    elements.append(title)
    elements.append(subtitle)
    elements.append(info)
    elements.append(Spacer(1, 20))

    # -------------------------------
    # Sensor Data Table
    # -------------------------------
    data = [
        ["Parameter", "Value"],
        ["Voltage (V)", voltage],
        ["Current (A)", current],
        ["Frequency (Hz)", frequency],
        ["Temperature (°C)", temperature],
        ["Detected Fault", fault],
        ["AI Confidence", f"{confidence:.2f}%"],
        ["Grid Health", f"{health}%"],
    ]

    table = Table(data, colWidths=[200, 200])

    table.setStyle(TableStyle([

        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#0B5394")),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),

        ('BACKGROUND', (0, 1), (0, -1), colors.HexColor("#D9EAF7")),

        ('GRID', (0, 0), (-1, -1), 1, colors.grey),

        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),

        ('FONTSIZE', (0, 0), (-1, -1), 11),

        ('BOTTOMPADDING', (0, 0), (-1, 0), 10),

        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),

        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    elements.append(table)

    elements.append(Spacer(1, 20))

# -------------------------------
# AI Prediction
# -------------------------------

    elements.append(
    Paragraph("<b>AI Prediction</b>", styles["Heading2"])
)

    prediction = f"""
<b>Predicted Fault:</b> {fault}<br/>
<b>Prediction Confidence:</b> {confidence:.2f}%<br/>
<b>Grid Health:</b> {health}%<br/>
"""

    elements.append(
    Paragraph(prediction, styles["BodyText"])
)

    elements.append(Spacer(1,20))

# -------------------------------
# AI Recommendation
# -------------------------------
   

   # -------------------------------
# Grid Status
# -------------------------------

    elements.append(
    Paragraph("<b>Grid Status</b>", styles["Heading2"])
)

    if health >= 80:
        status_text = "<font color='green'><b>🟢 GRID OPERATING NORMALLY</b></font>"
    else:
        status_text = "<font color='red'><b>🔴 EMERGENCY SHUTDOWN RECOMMENDED</b></font>"

    elements.append(
    Paragraph(status_text, styles["Heading2"])
)

    elements.append(Spacer(1,20))

    # -------------------------------
# GIS Map Snapshot
# -------------------------------

    elements.append(
        Paragraph("<b>GIS Disaster Intelligence Map</b>", styles["Heading2"])
    )

    elements.append(Spacer(1, 10))

    if os.path.exists("assets/gis_snapshot.png"):

        img = Image(
            "assets/gis_snapshot.png",
            width=450,
            height=300
        )

        elements.append(img)

    elements.append(Spacer(1, 20))

    

    # -------------------------------
    # Footer
    # -------------------------------
    footer = Paragraph(
        f"""
        <hr/>
        <b>Generated by GridGuard AI</b><br/>
        AI-Based LT Line Fault Detection & Automatic Emergency Shutdown<br/><br/>

        Report Generated:
        {datetime.now().strftime("%d-%m-%Y %H:%M:%S")}
        """,
        styles["Normal"]
    )

    elements.append(footer)
    # -------------------------------
    # Build PDF
    # -------------------------------
    doc.build(elements)

    return filename